export const PATH = {
  ROOT: "/",
  LOGIN: "/login",
  SIGNUP: "/login/signup",
  INTEREST: "/login/signup/interest",
  ERROR: "/error",
  MAIN: "/main",
  TAB: "/main/tab",
  HOME: "/main/tab/home",
  POPULAR_CHALLENGE: "/main/tab/popular",
  NEW_CHALLENGE: "/main/tab/new",
  SUGGESTION_CHALLENGE: "/main/tab/suggestion",
  SEARCH: "/main/search",
  ADMIN: "/admin",
  ADMIN_INSTANCE: "/admin/instance",
  ADMIN_INSTANCE_ID: "/admin/instance/:id",
};
