export const PATH = {
  LOGIN: "/",
  SIGNUP: "/login/signup",
  INTEREST: "/login/signup/interest",
  ERROR: "/error",
  MAIN: "/main",
  SEARCH: "/main/search",
  HOME: "/main/home",
  POPULAR_CHALLENGE: "/main/home/popular",
  NEW_CHALLENGE: "/main/home/new",
  SUGGESTION_CHALLENGE: "/main/home/suggestion",
  MY_CHALLENGE: "/main/my-challenge",
  PET: "/main/pet",
  MY_PAGE: "/main/my-page",
  ADMIN: "/admin",
  ADMIN_INSTANCE: "/admin/instance",
  ADMIN_INSTANCE_ID: "/admin/instance/:id",
};
