const requests = {
  fetchJwt: `/auth`,
  fetchTopic: `/admin/topic`,
  fetchInstance: `/admin/instance`,
  fetchChallenges: `/challenges`,
  fetchChallengesLatest: `/challenges/latest`,
  fetchChallengesActivity: `/challenges/my/activity`,
  fetchChallengesDone: `/challenges/my/done`,
  fetchChallengesPreActivity: `/challenges/my/pre-activity`,
  fetchChallengesReward: `/challenges/reward`,
  fetchChallengesPopular: `/challenges/popular`,
  fetchChallengesRecommend: `/challenges/recommend`,
  fetchChallengesSearch: `/challenges/search`,
  fetchProfile: `/profile`,
  fetchProfileInterest: `/profile/interest`,
  fetchProfileChallenges: `/profile/challenges`,
  fetchLikeChallenge: `/profile/likes`,
  fetchCert: `/certification`,
  fetchCertTotal: `/certification/total`,
  fetchCertInfo: `/certification/information`,
  fetchCertRepo: `/certification/repositories`,
  fetchCertPullReq: `/certification/verify/pull-request`,
  fetchCertWeek: `/certification/week`,
  fetchCertWeekAll: `/certification/week/all`,
  fetchCertVerifyToken: `/certification/verify/token`,
  fetchCertVerifyRepo: `/certification/verify/repository`,
  fetchCheckNickname: `/signup/check-nickname`,
};

export default requests;
